[Interface]
# Bouncing = 8
# NetShield = 1
# Moderate NAT = off
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = EPEbUGK4uMONMgCHNHX1sSj0w6BPG937k/e0mcLr3Vw=
Address = 10.2.0.2/32, 2a07:b944::2:2/128
DNS = 10.2.0.1, 2a07:b944::2:1

[Peer]
# CA#93
PublicKey = b5Wy36VwywSceq7wfLAe/QxcQ/UQC11txwkGes/CEWc=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 146.70.198.50:51820

# Uncomment the following line (delete the # symbol) to connect to Proton VPN using IPv6.
# Endpoint = [2a0d:5600:9:a24::10]:51820
PersistentKeepalive = 25