[Interface]
# Bouncing = 3
# NetShield = 1
# Moderate NAT = off
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = 2CHk2sF4zOIsHfTfNOGysY65klvV8jN53h6zyX8Wx0k=
Address = 10.2.0.2/32, 2a07:b944::2:2/128
DNS = 10.2.0.1, 2a07:b944::2:1

[Peer]
# DK#52
PublicKey = sbjnjFtxUz4dxYfNL7WOVf1StMjjAhkiPLCPtVtlhRI=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 193.29.107.162:51820

# Uncomment the following line (delete the # symbol) to connect to Proton VPN using IPv6.
# Endpoint = [2001:ac8:37:65::10]:51820
PersistentKeepalive = 25