[Interface]
# Bouncing = 5
# NetShield = 1
# Moderate NAT = off
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = MCV1kKt1wHNSsAhQNmSNzC2/aPdK5xfq6gGNxKU9Rms=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# ID#14
PublicKey = n1CXZzndn2AZaB60AqCCm1ksR0aZQoL6FGwk7UgI9xc=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 146.70.14.19:51820

PersistentKeepalive = 25