[Interface]
# Bouncing = 11
# NetShield = 1
# NAT trung bình = off
# NAT-PMP (Cổng chuyển tiếp) = off
# VPN Accelerator = on
PrivateKey = 0MVNizkSKPAJX9mXj0ps4LLNg/ClOK7+FVOtskduBE0=
Address = 10.2.0.2/32, 2a07:b944::2:2/128
DNS = 10.2.0.1, 2a07:b944::2:1

[Peer]
# KR#24
PublicKey = kwmJ9x2fBnD1PyYM9alhOW835krOfgVCr6ArMLA1pGk=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 79.110.55.2:51820
PersistentKeepalive = 25
