[Interface]
# Bouncing = 4
# NetShield = 1
# Moderate NAT = off
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = iF+pzl6BUm1xaaBzyhwfXYewDLZLiCTLnSDV4pLW53Y=
Address = 10.2.0.2/32, 2a07:b944::2:2/128
DNS = 10.2.0.1, 2a07:b944::2:1

[Peer]
# NZ#20
PublicKey = /QKfRMQaQKdQ4UAwmQc8KKShfc3Mjl1HcKiiGEoWwTU=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 116.90.74.178:51820

# Uncomment the following line (delete the # symbol) to connect to Proton VPN using IPv6.
# Endpoint = [2401:3bc0:700:231::10]:51820
PersistentKeepalive = 25