[Interface]
# Bouncing = 3
# NetShield = 1
# NAT trung bình = off
# NAT-PMP (Cổng chuyển tiếp) = off
# VPN Accelerator = on
PrivateKey = 0I53vjf9RXsDLkSvjgHDjJAyZrJM99ulOBwqZ5FdzXw=
Address = 10.2.0.2/32, 2a07:b944::2:2/128
DNS = 10.2.0.1, 2a07:b944::2:1

[Peer]
# US-AZ#84
PublicKey = qDJgY2K+GtC/geqxLN2ZO61LHlwENsMpapC1eGF21mM=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 193.37.254.66:51820
PersistentKeepalive = 25
