[Interface]
# Bouncing = 8
# NetShield = 1
# NAT trung bình = off
# NAT-PMP (Cổng chuyển tiếp) = off
# VPN Accelerator = on
PrivateKey = IM0kUaGxBQAPbhERRKHujObgaXEk24xQie7GSqEeQUo=
Address = 10.2.0.2/32, 2a07:b944::2:2/128
DNS = 10.2.0.1, 2a07:b944::2:1

[Peer]
# VN#9
PublicKey = NfKOMtk2fuDycbQXv36yk5mfdgDA8/8SN6amCdFrKxQ=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 188.214.152.226:51820
PersistentKeepalive = 25
