[Interface]
# Vietnam VN#8
PrivateKey = 0P1Ugh6sTE6NCYKLmJjB18WsICgJIMrt7tXM55yaHXo=
Address = 10.2.0.2/32, 2a07:b944::2:2/128
DNS = 10.2.0.1

[Peer]
PublicKey = NfKOMtk2fuDycbQXv36yk5mfdgDA8/8SN6amCdFrKxQ=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 188.214.152.226:51820
PersistentKeepalive = 25

[Socks5]
BindAddress = 0.0.0.0:25344

[http]
BindAddress = 0.0.0.0:25345
