[Interface]
# Bouncing = 7
# NetShield = 1
# Moderate NAT = off
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = 0LdQLef7hbc81iNTdFBUbXBnWCxwDe3OfB4JcSdkIVk=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# CH#289
PublicKey = WYXA8DeAZIF4th8Dfbw02osdbFc24sK10zKijcJvZwU=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 149.88.27.193:51820

PersistentKeepalive = 25

[Socks5]
BindAddress = 0.0.0.0:25388

[http]
BindAddress = 0.0.0.0:25389
