[Interface]
# Key for wireproxy-af1
# Bouncing = 0
# NetShield = 1
# NAT trung bình = off
# NAT-PMP (Cổng chuyển tiếp) = off
# VPN Accelerator = on
PrivateKey = cBjRTZBGnVax8ZToHo85+lM+EcLvGKNTGa1U4/aY0E4=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# AF#1
PublicKey = RY8jot0tZvug/zGd4SDBa5yFlMvhzYEto55QfMPSTG0=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 79.135.105.1:51820

PersistentKeepalive = 25

[Socks5]
BindAddress = 0.0.0.0:25446

[http]
BindAddress = 0.0.0.0:25447
