[Interface]
# Bouncing = 2
# NetShield = 1
# Moderate NAT = off
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = UCcN+cA5ZVKf2iUFx868Thy/AG8zKusOOxx1Sl+6F0M=
Address = 10.2.0.2/32, 2a07:b944::2:2/128
DNS = 10.2.0.1, 2a07:b944::2:1

[Peer]
# BE#43
PublicKey = s4t00o/80zIqjUYTSpavg5kQ1lYRV7DXL1/yTG67JQI=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 91.90.123.178:51820

# Uncomment the following line (delete the # symbol) to connect to Proton VPN using IPv6.
# Endpoint = [2001:ac8:27:42::10]:51820
PersistentKeepalive = 25

[Socks5]
BindAddress = 0.0.0.0:25396

[http]
BindAddress = 0.0.0.0:25397
