[Interface]
# Bouncing = 7
# NetShield = 1
# NAT trung bình = off
# NAT-PMP (Cổng chuyển tiếp) = off
# VPN Accelerator = on
PrivateKey = 0IdL8Z+8vwQeQIC5cs8XmJ3EdT/FfnkJzOqSKmrmKkQ=
Address = 10.2.0.2/32, 2a07:b944::2:2/128
DNS = 10.2.0.1, 2a07:b944::2:1

[Peer]
# UK#186
PublicKey = DgzYjQOQBgtBFUeyj3bVXpzl0qZE1I3/rk/IDS1b8kg=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 149.40.48.65:51820
PersistentKeepalive = 25

[Socks5]
BindAddress = 0.0.0.0:25358

[http]
BindAddress = 0.0.0.0:25359
