[Interface]
# Key for wireproxy-az2
# Bouncing = 1
# NetShield = 1
# NAT trung bình = off
# NAT-PMP (Cổng chuyển tiếp) = off
# VPN Accelerator = on
PrivateKey = wK629TJmHDYi+jmNH0qqW/M69nT8ZU9mDrTS5HJ3gEk=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# AZ#2
PublicKey = DhNpGwLwzXGSwKXySOUXcmJStXGoGdlrfPZUtmC1jwY=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 45.83.124.1:51820

PersistentKeepalive = 25

[Socks5]
BindAddress = 0.0.0.0:25466

[http]
BindAddress = 0.0.0.0:25467
