[Interface]
# Key for wireproxy-tw13
# Bouncing = 5
# NetShield = 1
# NAT trung bình = off
# NAT-PMP (Cổng chuyển tiếp) = off
# VPN Accelerator = on
PrivateKey = aBmsRyc9s5zF1yIcVSIx1ozWr2AeCflmzYGWJo9LIEI=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# TW#13
PublicKey = 4YvW6/5LP4g/WmaLc1EDfOno+IyN6r+87gQEqGz2Gz4=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 2.58.241.66:51820

PersistentKeepalive = 25

[Socks5]
BindAddress = 0.0.0.0:25440

[http]
BindAddress = 0.0.0.0:25441
