[Interface]
# Key for wireproxy-ao1
# Bouncing = 0
# NetShield = 1
# NAT trung bình = off
# NAT-PMP (Cổng chuyển tiếp) = off
# VPN Accelerator = on
PrivateKey = CIN2GPLuiXQrmg3hwceMvdMTVkGME2KATJEqRY09uU0=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# AO#1
PublicKey = eFEhiG7vdkDSwqtwOgECFE7x8Xr8NnJfh0QU1XK6jwA=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 79.135.105.12:51820

PersistentKeepalive = 25

[Socks5]
BindAddress = 0.0.0.0:25458

[http]
BindAddress = 0.0.0.0:25459
