[Interface]
# Bouncing = 2
# NetShield = 1
# Moderate NAT = off
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = 0NTfq8e/a0Tr4v/lqQ5K4wcWM0IenajLOGBAx1Zvk2Y=
Address = 10.2.0.2/32, 2a07:b944::2:2/128
DNS = 10.2.0.1, 2a07:b944::2:1

[Peer]
# TH#3
PublicKey = N4vu5ZFsvf3nbKAYnwwXvqeDwxrYOXZKbTSdknB9a1w=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 37.19.201.129:51820

# Uncomment the following line (delete the # symbol) to connect to Proton VPN using IPv6.
# Endpoint = [2a10:9007:5:10::10]:51820
PersistentKeepalive = 25

[Socks5]
BindAddress = 0.0.0.0:25382

[http]
BindAddress = 0.0.0.0:25383
