[Interface]
# Bouncing = 5
# NetShield = 1
# Moderate NAT = off
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = iLzixja8fqAEKIQ4yaL/TjvjfUTg5FXH6xTQq4InvX8=
Address = 10.2.0.2/32, 2a07:b944::2:2/128
DNS = 10.2.0.1, 2a07:b944::2:1

[Peer]
# VN#6
PublicKey = NfKOMtk2fuDycbQXv36yk5mfdgDA8/8SN6amCdFrKxQ=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 188.214.152.226:51820

# Uncomment the following line (delete the # symbol) to connect to Proton VPN using IPv6.
# Endpoint = [2001:ac8:93:3::10]:51820
PersistentKeepalive = 25

[Socks5]
BindAddress = 0.0.0.0:25416

[http]
BindAddress = 0.0.0.0:25417
