[Interface]
# US California US-CA#684
PrivateKey = QFXYB/1dULhDXccAO6rrjm8jk5x0hS/Wl0pHYMG9umI=
Address = 10.2.0.2/32, 2a07:b944::2:2/128
DNS = 10.2.0.1

[Peer]
PublicKey = gllq5CYSNwqDgciSMo/gDAwS9b5bS1lch2eOlBdPL2E=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 149.102.228.193:51820
PersistentKeepalive = 25

[Socks5]
BindAddress = 0.0.0.0:25350

[http]
BindAddress = 0.0.0.0:25351
