[Interface]
# Key for wireproxy-al26
# Bouncing = 1
# NetShield = 1
# NAT trung bình = off
# NAT-PMP (Cổng chuyển tiếp) = off
# VPN Accelerator = on
PrivateKey = MNFv5CS3wDJ9gnkDPmo3gEsGSNbL6nUndDf/XhdemkU=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# AL#26
PublicKey = D6VgBbcmr53evqwGGsdZNDneeg4tlag/KQ3+glPJ9js=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 79.135.105.4:51820

PersistentKeepalive = 25

[Socks5]
BindAddress = 0.0.0.0:25450

[http]
BindAddress = 0.0.0.0:25451
