[Interface]
# Singapore SG#196
PrivateKey = SIymSRTLaYZoCg/jtuNP1C+2p4wKj4hTjz4rcznyJnc=
Address = 10.2.0.2/32, 2a07:b944::2:2/128
DNS = 10.2.0.1

[Peer]
PublicKey = MsgCxkI8hLSpeEh9ttQjx7FT9Hu/R3WEUyF0YomZlCE=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 149.50.211.166:51820
PersistentKeepalive = 25

[Socks5]
BindAddress = 0.0.0.0:25346

[http]
BindAddress = 0.0.0.0:25347
