[Interface]
# Key for wireproxy-hk29
# Bouncing = 1
# NetShield = 1
# NAT trung bình = off
# NAT-PMP (Cổng chuyển tiếp) = off
# VPN Accelerator = on
PrivateKey = *****
Address = 10.2.0.2/32, 2a07:b944::2:2/128
DNS = 10.2.0.1, 2a07:b944::2:1

[Peer]
# HK#29
PublicKey = giBCbR12im6jWSvwEQ0mJ1PH8NUhRFUDedozBSYC8n4=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 146.70.113.114:51820

# Uncomment the following line (delete the # symbol) to connect to Proton VPN using IPv6.
# Endpoint = [2001:ac8:93:3::10]:51820
PersistentKeepalive = 25

[Socks5]
BindAddress = 0.0.0.0:25436

[http]
BindAddress = 0.0.0.0:25437
