[Interface]
# Key for wireproxy-id14
# Bouncing = 5
# NetShield = 1
# NAT trung bình = off
# NAT-PMP (Cổng chuyển tiếp) = off
# VPN Accelerator = on
PrivateKey = 8B4wMppD4duutzeDkVzoExs+4Y2aDdx5+20fgC9gH30=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# ID#14
PublicKey = n1CXZzndn2AZaB60AqCCm1ksR0aZQoL6FGwk7UgI9xc=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 146.70.14.19:51820

PersistentKeepalive = 25

[Socks5]
BindAddress = 0.0.0.0:25452

[http]
BindAddress = 0.0.0.0:25453
