[Interface]
# Key for wireproxy-my21
# Bouncing = 12
# NetShield = 1
# NAT trung bình = off
# NAT-PMP (Cổng chuyển tiếp) = off
# VPN Accelerator = on
PrivateKey = mK10oruq9xgMd2bMBLVfBa9hc4kC9yVEIfpv8Qzean4=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# MY#21
PublicKey = JMGP8LdMl8N5Q8lXt25cPpvMcWvzoVjP/bAZ+88LUCM=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 45.83.126.1:51820

PersistentKeepalive = 25

[Socks5]
BindAddress = 0.0.0.0:25474

[http]
BindAddress = 0.0.0.0:25475
