[Interface]
# Key for wireproxy-ph2
# Bouncing = 1
# NetShield = 1
# NAT trung bình = off
# NAT-PMP (Cổng chuyển tiếp) = off
# VPN Accelerator = on
PrivateKey = cCm9LdQpTFDmdxXUL6S3t8RoVSLfzLZVN8cdTPOqxXA=
Address = 10.2.0.2/32, 2a07:b944::2:2/128
DNS = 10.2.0.1, 2a07:b944::2:1

[Peer]
# PH#2
PublicKey = YHiExIkSK5Jqk/P6zO3UIDmf4B5NgClT2hqOXYCxD0g=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 188.214.125.162:51820

# Uncomment the following line (delete the # symbol) to connect to Proton VPN using IPv6.
# Endpoint = [2001:ac8:94:3::10]:51820
PersistentKeepalive = 25

[Socks5]
BindAddress = 0.0.0.0:25488

[http]
BindAddress = 0.0.0.0:25489
