[Interface]
# Bouncing = 11
# NetShield = 1
# Moderate NAT = off
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = cGu0xwpvfoDKOeCTR8X8wZr4f1hsntKrsLmVmKXVFG8=
Address = 10.2.0.2/32, 2a07:b944::2:2/128
DNS = 10.2.0.1, 2a07:b944::2:1

[Peer]
# BR#20
PublicKey = PNVnFfj4CzrNmhx1E5yCKjXq8253OA1CJ4a5mFHGNFQ=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 188.241.177.226:51820

# Uncomment the following line (delete the # symbol) to connect to Proton VPN using IPv6.
# Endpoint = [2a0d:5600:35:3::10]:51820
PersistentKeepalive = 25

[Socks5]
BindAddress = 0.0.0.0:25408

[http]
BindAddress = 0.0.0.0:25409
