[Interface]
# Key for wireproxy-pool
# Bouncing = 7
# NetShield = 1
# NAT trung bình = off
# NAT-PMP (Cổng chuyển tiếp) = off
# VPN Accelerator = on
PrivateKey = 2IeWk0Vf6KWe1V7OBPMFrvV/7d2rPo+eH7xUXxS3u1c=
Address = 10.2.0.2/32, 2a07:b944::2:2/128
DNS = 10.2.0.1, 2a07:b944::2:1

[Peer]
# HK#35
PublicKey = giBCbR12im6jWSvwEQ0mJ1PH8NUhRFUDedozBSYC8n4=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 146.70.113.114:51820
PersistentKeepalive = 25

[Socks5]
BindAddress = 0.0.0.0:25352

[http]
BindAddress = 0.0.0.0:25353
