[Interface]
# Key for wireproxy-pl52
# Bouncing = 3
# NetShield = 1
# NAT trung bình = off
# NAT-PMP (Cổng chuyển tiếp) = off
# VPN Accelerator = on
PrivateKey = MINrQn6ozwt4c9i6+hxCrJHyFVXa04rQf5lxv0Dno14=
Address = 10.2.0.2/32, 2a07:b944::2:2/128
DNS = 10.2.0.1, 2a07:b944::2:1

[Peer]
# PL#52
PublicKey = bIMk4w3SJ9OLWqlwgCB+umYlRoaLQRk1Te4rUVjVLEI=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 146.70.161.178:51820

# Uncomment the following line (delete the # symbol) to connect to Proton VPN using IPv6.
# Endpoint = [2a0d:5600:13:28::10]:51820
PersistentKeepalive = 25

[Socks5]
BindAddress = 0.0.0.0:25468

[http]
BindAddress = 0.0.0.0:25469
