[Interface]
# Bouncing = 2
# NetShield = 1
# Moderate NAT = off
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = qFo5qX1HVh21znE0TbPuHPuDLqmVPCL2P4k+sJSQ3n8=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# MY#11
PublicKey = JMGP8LdMl8N5Q8lXt25cPpvMcWvzoVjP/bAZ+88LUCM=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 45.83.126.1:51820

PersistentKeepalive = 25

[Socks5]
BindAddress = 0.0.0.0:25384

[http]
BindAddress = 0.0.0.0:25385
