[Interface]
# Japan JP#288
PrivateKey = 8IJlId6K9JwZ1xwjA8XlVefbtYeCJX/igiPTBIVCm1Q=
Address = 10.2.0.2/32, 2a07:b944::2:2/128
DNS = 10.2.0.1

[Peer]
PublicKey = BkgDHEcC60DJjSseQB+/IkApYytVIMYa2vcOTqde0xQ=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 138.199.21.214:51820
PersistentKeepalive = 25

[Socks5]
BindAddress = 0.0.0.0:25348

[http]
BindAddress = 0.0.0.0:25349
