[Interface]
# Key for wireproxy-by25
# Bouncing = 0
# NetShield = 1
# NAT trung bình = off
# NAT-PMP (Cổng chuyển tiếp) = off
# VPN Accelerator = on
PrivateKey = qKVFmgNxhd/Tnl8FwxikW/Nf3aZ6Hy/5r+UrH/llpF8=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# BY#25
PublicKey = RUHO1OX9FqSvvJ+Ec8q2a2p6wnuvoMKx3Z2Op94qaCI=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 79.135.105.24:51820

PersistentKeepalive = 25

[Socks5]
BindAddress = 0.0.0.0:25476

[http]
BindAddress = 0.0.0.0:25477
