[Interface]
# Bouncing = 9
# NetShield = 1
# Moderate NAT = off
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = YCclrfEP12rnMeur7VxAtp6GxQujj/Mjr87pHXJzVHM=
Address = 10.2.0.2/32, 2a07:b944::2:2/128
DNS = 10.2.0.1, 2a07:b944::2:1

[Peer]
# FR#167
PublicKey = zeGY3uQTDqTiaxp6vGqFzXck1TPNnzY+JZ2iNI2BrRU=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 146.70.194.98:51820

# Uncomment the following line (delete the # symbol) to connect to Proton VPN using IPv6.
# Endpoint = [2001:ac8:25:67::10]:51820
PersistentKeepalive = 25

[Socks5]
BindAddress = 0.0.0.0:25376

[http]
BindAddress = 0.0.0.0:25377
