[Interface]
# Bouncing = 3
# NetShield = 1
# Moderate NAT = off
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = uKZmoP6NLihdH3xtAxpc4ghWlqO5i2w1bhDaGDGhVWA=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# FI#1
PublicKey = z0xd29K3h6taRG+nGSvkgPXXzAOt+2V69dZTtjGoajs=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 194.34.132.55:51820

PersistentKeepalive = 25

[Socks5]
BindAddress = 0.0.0.0:25402

[http]
BindAddress = 0.0.0.0:25403
