[Interface]
# Key for wireproxy-ar31
# Bouncing = 6
# NetShield = 1
# NAT trung bình = off
# NAT-PMP (Cổng chuyển tiếp) = off
# VPN Accelerator = on
PrivateKey = 8HwLqRyhr8n+2O3pHfUMRacr4csbNHSJwdg240iHalc=
Address = 10.2.0.2/32, 2a07:b944::2:2/128
DNS = 10.2.0.1, 2a07:b944::2:1

[Peer]
# AR#31
PublicKey = pPR96SBtq9grARK6XDm5WI3XP1d8Le19Jl/HA9p7o00=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 149.102.224.161:51820

# Uncomment the following line (delete the # symbol) to connect to Proton VPN using IPv6.
# Endpoint = [2a10:9007:3::10]:51820
PersistentKeepalive = 25

[Socks5]
BindAddress = 0.0.0.0:25462

[http]
BindAddress = 0.0.0.0:25463
