[Interface]
# Bouncing = 13
# NetShield = 1
# Moderate NAT = off
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = oLqEI9R/6S7m8k854beCxpGQFIV8Y++lW080ZDHvYlA=
Address = 10.2.0.2/32, 2a07:b944::2:2/128
DNS = 10.2.0.1, 2a07:b944::2:1

[Peer]
# ES#71
PublicKey = mqt1HzBNMiBX2H9HOSUze4VXneRScc910/6qq2qPySc=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 37.19.214.1:51820

# Uncomment the following line (delete the # symbol) to connect to Proton VPN using IPv6.
# Endpoint = [2a02:6ea0:c31f:2064::10]:51820
PersistentKeepalive = 25

[Socks5]
BindAddress = 0.0.0.0:25394

[http]
BindAddress = 0.0.0.0:25395
